var data=[
 {
   "PRODUCT": "H27U1G8F2B",
   "TECH.": "4xnm",
   "DENSITY": "1Gb",
   "BLOCK SIZE": "128KB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "TSOP/FBGA",
   "AVAIL.": "Now",
   "REMARK": "-",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27S1G8F2B",
   "TECH.": "4xnm",
   "DENSITY": "1Gb",
   "BLOCK SIZE": "128KB",
   "STACK": "SDP",
   "VCC_ORG": "1.8V / x8",
   "PKG.": "TSOP/FBGA",
   "AVAIL.": "Now",
   "REMARK": "-",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27U1G8F2C",
   "TECH.": "3xnm",
   "DENSITY": "1Gb",
   "BLOCK SIZE": "128KB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "TSOP/FBGA",
   "AVAIL.": "Now",
   "REMARK": "-",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27S1G8F2C",
   "TECH.": "3xnm",
   "DENSITY": "1Gb",
   "BLOCK SIZE": "128KB",
   "STACK": "SDP",
   "VCC_ORG": "1.8V / x8",
   "PKG.": "TSOP/FBGA",
   "AVAIL.": "Now",
   "REMARK": "-",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27U2G8F2C",
   "TECH.": "4ynm",
   "DENSITY": "2Gb",
   "BLOCK SIZE": "128KB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "TSOP",
   "AVAIL.": "Now",
   "REMARK": "-",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27S2G8F2C",
   "TECH.": "4ynm",
   "DENSITY": "2Gb",
   "BLOCK SIZE": "128KB",
   "STACK": "SDP",
   "VCC_ORG": "1.8V / x8",
   "PKG.": "TSOP/FBGA",
   "AVAIL.": "Now",
   "REMARK": "-",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27U2G8F2D",
   "TECH.": "3xnm",
   "DENSITY": "2Gb",
   "BLOCK SIZE": "128KB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "TSOP",
   "AVAIL.": "Now",
   "REMARK": "-",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27S2G8F2D",
   "TECH.": "3xnm",
   "DENSITY": "2Gb",
   "BLOCK SIZE": "128KB",
   "STACK": "SDP",
   "VCC_ORG": "1.8V / x8",
   "PKG.": "TSOP",
   "AVAIL.": "Now",
   "REMARK": "-",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27U4G8F2D",
   "TECH.": "4ynm",
   "DENSITY": "4Gb",
   "BLOCK SIZE": "128KB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "TSOP",
   "AVAIL.": "Now",
   "REMARK": "-",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27U4G8F2E",
   "TECH.": "3xnm",
   "DENSITY": "4Gb",
   "BLOCK SIZE": "128KB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "TSOP",
   "AVAIL.": "Now",
   "REMARK": "-",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27S4G8F2E",
   "TECH.": "3xnm",
   "DENSITY": "4Gb",
   "BLOCK SIZE": "128KB",
   "STACK": "SDP",
   "VCC_ORG": "1.8V / x8",
   "PKG.": "TSOP",
   "AVAIL.": "Now",
   "REMARK": "-",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27U4G(O/8)F2G",
   "TECH.": "1xnm",
   "DENSITY": "4Gb",
   "BLOCK SIZE": "256KB/128KB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "TSOP",
   "AVAIL.": "Q1’18",
   "REMARK": "O:4KB/8:2KB",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27U8G(O/8)G5G",
   "TECH.": "1xnm",
   "DENSITY": "4Gb",
   "BLOCK SIZE": "256KB/128KB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "TSOP",
   "AVAIL.": "Q1’18",
   "REMARK": "O:4KB/8:2KB",
   "TYPE": "SLC"
 },
 {
   "PRODUCT": "H27QCG8T2E",
   "TECH.": "1xnm",
   "DENSITY": "64Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QDG8UDE",
   "TECH.": "1xnm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QEG8VEE",
   "TECH.": "1xnm",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QFG8YEE",
   "TECH.": "1xnm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QCG8T2F",
   "TECH.": "1xnm",
   "DENSITY": "64Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QDG8UDF",
   "TECH.": "1xnm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QEG8VEF",
   "TECH.": "1xnm",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QFG8YEF",
   "TECH.": "1xnm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QDG8T2B",
   "TECH.": "1xnm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QEG8UDB",
   "TECH.": "1xnm",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QFG8VEB",
   "TECH.": "1xnm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27Q1T8YEB",
   "TECH.": "1xnm",
   "DENSITY": "1024Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QFG8VQB",
   "TECH.": "1xnm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27Q1T8YQB",
   "TECH.": "1xnm",
   "DENSITY": "1024Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27Q2T8CQB",
   "TECH.": "1xnm",
   "DENSITY": "2048Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "16DP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QFG84EB",
   "TECH.": "1xnm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27Q1T85EB",
   "TECH.": "1xnm",
   "DENSITY": "1024Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27Q2T87EB",
   "TECH.": "1xnm",
   "DENSITY": "2048Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "16DP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QFG8PEM",
   "TECH.": "1xnm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27Q1T8QEM",
   "TECH.": "1xnm",
   "DENSITY": "1024Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QCG882M",
   "TECH.": "1xnm",
   "DENSITY": "64Gb",
   "BLOCK SIZE": "6MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QDG89DM",
   "TECH.": "1xnm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "6MB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27TDG8T2D",
   "TECH.": "1ynm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "6MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27TEG8U5D",
   "TECH.": "1ynm",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "6MB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27TFG8VFD",
   "TECH.": "1ynm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "6MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QDG8T2C",
   "TECH.": "3D-V2",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "9MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QEG8UDC",
   "TECH.": "3D-V2",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "9MB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QFG8VEC",
   "TECH.": "3D-V2",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "9MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27Q1T8YEC",
   "TECH.": "3D-V2",
   "DENSITY": "1024Gb",
   "BLOCK SIZE": "9MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27Q2T8CEC",
   "TECH.": "3D-V2",
   "DENSITY": "2048Gb",
   "BLOCK SIZE": "9MB",
   "STACK": "16DP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H25QEM8A1B",
   "TECH.": "3D-V4",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "19MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Q4'18",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "MLC"
 },
 {
   "PRODUCT": "H27QDG8M2M",
   "TECH.": "1xnm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27QEG8NDM",
   "TECH.": "1xnm",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27QFG8PEM",
   "TECH.": "1xnm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27Q1T8QEM",
   "TECH.": "1xnm",
   "DENSITY": "1Tb",
   "BLOCK SIZE": "4MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27QCG882M",
   "TECH.": "1xnm",
   "DENSITY": "64Gb",
   "BLOCK SIZE": "6MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27QDG8M2B",
   "TECH.": "1ynm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "6MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27QEG8NDB",
   "TECH.": "1ynm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "6MB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27QFG8PEB",
   "TECH.": "1ynm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "6MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(132ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27QEG8M2A",
   "TECH.": "3D-V4",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27QFG8NDA",
   "TECH.": "3D-V4",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27Q1T8PEA",
   "TECH.": "3D-V4",
   "DENSITY": "1024Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27Q2T8QEA",
   "TECH.": "3D-V4",
   "DENSITY": "2048Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27Q2T8QAA",
   "TECH.": "3D-V4",
   "DENSITY": "2048Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27Q4T8LEA",
   "TECH.": "3D-V4",
   "DENSITY": "4096Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "16DP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27Q4T8LAA",
   "TECH.": "3D-V4",
   "DENSITY": "4096Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "16DP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27Q1T8PQA",
   "TECH.": "3D-V4",
   "DENSITY": "1024Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(316ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27Q2T8QQA",
   "TECH.": "3D-V4",
   "DENSITY": "2048Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(316ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H27Q4T8LQA",
   "TECH.": "3D-V4",
   "DENSITY": "4096Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "16DP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(316ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFT8A1A",
   "TECH.": "3D-V4",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFT8B3A",
   "TECH.": "3D-V4",
   "DENSITY": "1024Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFT8D4A",
   "TECH.": "3D-V4",
   "DENSITY": "2048Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFT8F4A",
   "TECH.": "3D-V4",
   "DENSITY": "4096Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFT8F6A",
   "TECH.": "3D-V4",
   "DENSITY": "4096Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFT8G4A",
   "TECH.": "3D-V4",
   "DENSITY": "8192Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "16DP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFTMA1A",
   "TECH.": "3D-V4",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFTMB3A",
   "TECH.": "3D-V4",
   "DENSITY": "1024Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "DDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFTMD4A",
   "TECH.": "3D-V4",
   "DENSITY": "2048Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "QDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFTMF4A",
   "TECH.": "3D-V4",
   "DENSITY": "4096Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFTMF6A",
   "TECH.": "3D-V4",
   "DENSITY": "4096Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "ODP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25QFTMG4A",
   "TECH.": "3D-V4",
   "DENSITY": "8192Gb",
   "BLOCK SIZE": "13.5MB",
   "STACK": "16DP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Now",
   "REMARK": "HS(Toggle2.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H25BFT8A1M",
   "TECH.": "3D-V5",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "18MB",
   "STACK": "SDP",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "FBGA(152ball)",
   "AVAIL.": "Q1'19",
   "REMARK": "HS(Toggle3.0)",
   "TYPE": "TLC"
 },
 {
   "PRODUCT": "H2JTCG8T21BMR",
   "TECH.": "1xnm",
   "DENSITY": "64Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "1",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "Non Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTDG8UD1BMR",
   "TECH.": "1xnm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "2",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "Non Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTEG8VD1BMR",
   "TECH.": "1xnm",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "4",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "Non Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTFG8YD1BMR",
   "TECH.": "1xnm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "8",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "Non Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTDG8UD1BMS",
   "TECH.": "1xnm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "2",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "EMI Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTEG8VD1BMS",
   "TECH.": "1xnm",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "4",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "EMI Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTFG8YD1BMS",
   "TECH.": "1xnm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "8",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "EMI Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTCG8T21CMR",
   "TECH.": "1xnm",
   "DENSITY": "64Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "1",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "Non Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTFG8YD1CMR",
   "TECH.": "1xnm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "8",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "Non Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTFG8YD1CMS",
   "TECH.": "1xnm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "8",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "EMI Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JT1T8QD1MMS",
   "TECH.": "1xnm",
   "DENSITY": "1024Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "8",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "EMI Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTDG8UD1CMR",
   "TECH.": "1ynm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "2",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "Non Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTEG8VD1CMR",
   "TECH.": "1ynm",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "4",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "Non Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTDG8UD1CMS",
   "TECH.": "1ynm",
   "DENSITY": "128Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "2",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "EMI Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTEG8VD1CMS",
   "TECH.": "1ynm",
   "DENSITY": "256Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "4",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "EMI Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTFG8PD1MMR",
   "TECH.": "1ynm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "4",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "Non Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JT1T8QD1MMR",
   "TECH.": "1ynm",
   "DENSITY": "1024Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "8",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "Non Shielded",
   "TYPE": "E3NAND"
 },
 {
   "PRODUCT": "H2JTFG8PD1MMS",
   "TECH.": "1ynm",
   "DENSITY": "512Gb",
   "BLOCK SIZE": "4MB",
   "STACK": "4",
   "VCC_ORG": "3.3V / x8",
   "PKG.": "WLGA",
   "AVAIL.": "Now",
   "REMARK": "EMI Shielded",
   "TYPE": "E3NAND"
 }
];
var x="";
/*for (i in data){
   x+="<h2>" + data.PRODUCT+"</h2>"
}
document.getElementById("demo").innerHTML = x;*/
var typeGroup = document.getElementsByName('typeGroup');
function switchMode(){
   for (var i=0;i<typeGroup.length;i++) {
   
      if (typeGroup[i].checked) {
         
      if(typeGroup[i].value == "Flash"){
         document.getElementById("mainTable").style.visibility="hidden";
         document.getElementById("flashTable").style.visibility="visible";
      }else{
         document.getElementById("mainTable").style.visibility="visible";
         document.getElementById("flashTable").style.visibility="hidden";
      }
   }
   }
}
//console.log("here");
console.log(data[3].PRODUCT);